"""
nutri_ai/nutrition_data.py
──────────────────────────
Single nutrition database shared by:
  • mcp_server.py  (exposed as MCP tools)
  • tools.py       (used as inline FunctionTools for agents)

All values per standard Indian serving (noted in serving_g).
Source: ICMR 2020 nutritional tables + standard Indian recipe databases.
"""

# Per-dish nutrition data
DISHES: dict[str, dict] = {
    "butter chicken": {
        "name": "Butter Chicken (Murgh Makhani)",
        "region": "North India",
        "type": "chicken",
        "serving_g": 200,
        "calories": 320,
        "protein_g": 28,
        "carbs_g": 12,
        "fat_g": 18,
        "fiber_g": 2.0,
        "iron_mg": 2.1,
        "calcium_mg": 45,
        "sodium_mg": 680,
    },
    "chicken tikka masala": {
        "name": "Chicken Tikka Masala",
        "region": "North India",
        "type": "chicken",
        "serving_g": 200,
        "calories": 300,
        "protein_g": 30,
        "carbs_g": 14,
        "fat_g": 15,
        "fiber_g": 2.0,
        "iron_mg": 2.3,
        "calcium_mg": 50,
        "sodium_mg": 720,
    },
    "tandoori chicken": {
        "name": "Tandoori Chicken",
        "region": "North India (Punjab)",
        "type": "chicken",
        "serving_g": 200,
        "calories": 280,
        "protein_g": 38,
        "carbs_g": 5,
        "fat_g": 12,
        "fiber_g": 1.0,
        "iron_mg": 2.8,
        "calcium_mg": 42,
        "sodium_mg": 720,
    },
    "chicken korma": {
        "name": "Chicken Korma",
        "region": "Mughlai / North India",
        "type": "chicken",
        "serving_g": 200,
        "calories": 360,
        "protein_g": 27,
        "carbs_g": 11,
        "fat_g": 24,
        "fiber_g": 1.5,
        "iron_mg": 1.9,
        "calcium_mg": 65,
        "sodium_mg": 590,
    },
    "chicken biryani": {
        "name": "Chicken Biryani",
        "region": "Pan-India",
        "type": "chicken",
        "serving_g": 350,
        "calories": 520,
        "protein_g": 35,
        "carbs_g": 58,
        "fat_g": 16,
        "fiber_g": 3.0,
        "iron_mg": 3.2,
        "calcium_mg": 55,
        "sodium_mg": 780,
    },
    "chettinad chicken": {
        "name": "Chettinad Chicken Curry",
        "region": "Tamil Nadu",
        "type": "chicken",
        "serving_g": 200,
        "calories": 290,
        "protein_g": 28,
        "carbs_g": 9,
        "fat_g": 17,
        "fiber_g": 2.5,
        "iron_mg": 2.4,
        "calcium_mg": 48,
        "sodium_mg": 640,
    },
    "mutton biryani": {
        "name": "Mutton Biryani",
        "region": "Hyderabad / Pan-India",
        "type": "mutton",
        "serving_g": 350,
        "calories": 580,
        "protein_g": 32,
        "carbs_g": 62,
        "fat_g": 22,
        "fiber_g": 3.0,
        "iron_mg": 4.5,
        "calcium_mg": 60,
        "sodium_mg": 820,
    },
    "rogan josh": {
        "name": "Rogan Josh",
        "region": "Kashmir",
        "type": "mutton",
        "serving_g": 200,
        "calories": 340,
        "protein_g": 29,
        "carbs_g": 10,
        "fat_g": 21,
        "fiber_g": 2.5,
        "iron_mg": 4.2,
        "calcium_mg": 55,
        "sodium_mg": 700,
    },
    "keema matar": {
        "name": "Keema Matar (Minced Mutton with Peas)",
        "region": "North India",
        "type": "mutton",
        "serving_g": 200,
        "calories": 380,
        "protein_g": 31,
        "carbs_g": 16,
        "fat_g": 22,
        "fiber_g": 4.0,
        "iron_mg": 4.8,
        "calcium_mg": 40,
        "sodium_mg": 650,
    },
    "fish curry": {
        "name": "Fish Curry (Machhi Ka Salan)",
        "region": "Pan-India",
        "type": "fish",
        "serving_g": 200,
        "calories": 240,
        "protein_g": 26,
        "carbs_g": 8,
        "fat_g": 12,
        "fiber_g": 1.5,
        "iron_mg": 1.8,
        "calcium_mg": 80,
        "sodium_mg": 560,
    },
    "goan fish curry": {
        "name": "Goan Fish Curry",
        "region": "Goa",
        "type": "fish",
        "serving_g": 200,
        "calories": 260,
        "protein_g": 24,
        "carbs_g": 10,
        "fat_g": 14,
        "fiber_g": 2.0,
        "iron_mg": 2.0,
        "calcium_mg": 90,
        "sodium_mg": 610,
    },
    "prawn masala": {
        "name": "Prawn Masala",
        "region": "Coastal India",
        "type": "seafood",
        "serving_g": 180,
        "calories": 220,
        "protein_g": 24,
        "carbs_g": 8,
        "fat_g": 11,
        "fiber_g": 1.5,
        "iron_mg": 3.5,
        "calcium_mg": 95,
        "sodium_mg": 700,
    },
    "egg bhurji": {
        "name": "Egg Bhurji (Anda Bhurji)",
        "region": "Pan-India",
        "type": "egg",
        "serving_g": 150,
        "calories": 220,
        "protein_g": 14,
        "carbs_g": 6,
        "fat_g": 16,
        "fiber_g": 1.0,
        "iron_mg": 2.0,
        "calcium_mg": 60,
        "sodium_mg": 480,
    },
    "egg curry": {
        "name": "Egg Curry (Anda Masala)",
        "region": "Pan-India",
        "type": "egg",
        "serving_g": 200,
        "calories": 250,
        "protein_g": 16,
        "carbs_g": 10,
        "fat_g": 17,
        "fiber_g": 2.0,
        "iron_mg": 2.2,
        "calcium_mg": 70,
        "sodium_mg": 520,
    },
    "boiled rice": {
        "name": "Boiled Basmati Rice",
        "region": "Pan-India",
        "type": "carb",
        "serving_g": 150,
        "calories": 195,
        "protein_g": 4,
        "carbs_g": 43,
        "fat_g": 0.5,
        "fiber_g": 1.0,
        "iron_mg": 0.8,
        "calcium_mg": 10,
        "sodium_mg": 5,
    },
    "roti": {
        "name": "Whole Wheat Roti / Chapati",
        "region": "Pan-India",
        "type": "carb",
        "serving_g": 40,
        "calories": 100,
        "protein_g": 3,
        "carbs_g": 20,
        "fat_g": 1.5,
        "fiber_g": 2.5,
        "iron_mg": 1.2,
        "calcium_mg": 20,
        "sodium_mg": 10,
    },
    "raita": {
        "name": "Cucumber / Boondi Raita",
        "region": "Pan-India",
        "type": "side",
        "serving_g": 100,
        "calories": 80,
        "protein_g": 4,
        "carbs_g": 9,
        "fat_g": 3,
        "fiber_g": 0.5,
        "iron_mg": 0.2,
        "calcium_mg": 120,
        "sodium_mg": 200,
    },
}

# ICMR 2020 daily recommended values for a sedentary adult Indian
DAILY_RDA = {
    "calories":    2000,
    "protein_g":   60,
    "carbs_g":     270,
    "fat_g":       67,
    "fiber_g":     30,
    "iron_mg":     17,
    "calcium_mg":  1000,
    "sodium_mg":   2000,
}


def fuzzy_lookup(query: str) -> dict | None:
    """Return dish data for the closest matching key, or None."""
    q = query.lower().strip()
    # Exact match first
    if q in DISHES:
        return DISHES[q]
    # Substring match
    for key, data in DISHES.items():
        if key in q or q in key:
            return data
    # Word overlap
    q_words = set(q.split())
    for key, data in DISHES.items():
        if q_words & set(key.split()):
            return data
    return None
